# Nome do compilador
CXX = g++

# Alvo principal
all: programa

# Regra para gerar o executável
programa: kruskal.cpp
	$(CXX) -o kruskal kruskal.cpp

# Limpeza de arquivos gerados
clean:
	rm -f kruskal
