# Nome do compilador
CXX = g++

# Alvo principal
all: programa

# Regra para gerar o executável
programa: dijkstra.cpp
	$(CXX) -o dijkstra dijkstra.cpp

# Limpeza de arquivos gerados
clean:
	rm -f dijkstra
