# Nome do compilador
CXX = g++

# Alvo principal
all: programa

# Regra para gerar o executável
programa: kosaraju.cpp
	$(CXX) -o kosaraju kosaraju.cpp

# Limpeza de arquivos gerados
clean:
	rm -f kosaraju
